/**
 * Vertical Catalog — Multi-Vertical AI Sales Engine
 *
 * Config-driven marketplace of verticals. The catalog is DATA, not code:
 * add a category/vertical by registering a `VerticalDefinition` and the
 * engine adapts with zero rewrites.
 *
 * Shared per-category signal banks keep the catalog DRY while letting
 * each vertical override or extend its own signals.
 */

import type {
  SignalDef,
  VerticalCategoryId,
  VerticalDefinition,
} from './types';

function s(id: string, label: string, weight: number): SignalDef {
  return { id, label, weight };
}

// ── Shared signal banks ────────────────────────────────────────────

const HOME_SERVICE_SIGNALS = {
  pain: [
    s('emergency_demand', 'Emergency/service-call demand spikes', 0.3),
    s('no_online_booking', 'No online booking or lead capture', 0.25),
    s('manual_dispatch', 'Manual tech dispatch & paper estimates', 0.2),
    s('missed_calls', 'After-hours calls go unanswered', 0.15),
    s('no_maintenance_plan', 'No recurring maintenance/plan revenue', 0.1),
  ],
  buying: [
    s('high_review_volume', 'Strong review volume (proof of demand)', 0.3),
    s('multiple_locations', 'Multiple locations/service areas', 0.25),
    s('growing_labor', 'Many technicians/labor headcount', 0.2),
    s('recurring_service', 'Recurring service relationships', 0.15),
    s('recent_activity', 'Recent review/activity signals', 0.1),
  ],
  ai: [
    s('ai_receptionist', 'AI voice receptionist / missed-call recovery', 0.3),
    s('booking_automation', 'AI appointment scheduling & rescheduling', 0.25),
    s('followup_automation', 'Automated lead follow-up & win-back', 0.2),
    s('estimate_assist', 'AI estimate/quote assist', 0.15),
    s('dispatch_automation', 'Dispatch & job-note automation', 0.1),
  ],
  web: [
    s('outdated_site', 'Outdated website', 0.3),
    s('no_mobile', 'Not mobile optimized', 0.2),
    s('no_lead_form', 'No lead-capture form/chat', 0.25),
    s('no_seo', 'Weak local SEO / no booking', 0.25),
  ],
  automation: [
    s('manual_dispatch_auto', 'Manual dispatch & scheduling', 0.3),
    s('manual_invoicing', 'Manual quoting/invoicing', 0.25),
    s('no_crm', 'No CRM / leads in a spreadsheet', 0.25),
    s('paper_workflow', 'Paper-heavy field workflow', 0.2),
  ],
  app: [
    s('booking_app', 'Customer booking/portal app', 0.3),
    s('field_app', 'Field tech mobile app', 0.25),
    s('internal_tool', 'Internal operational tool', 0.2),
    s('ops_dashboard', 'Owner/ops dashboard', 0.25),
  ],
};

const HEALTH_WELLNESS_SIGNALS = {
  pain: [
    s('manual_booking', 'Manual booking/contact workflow', 0.3),
    s('no_shows', 'No-show / last-minute cancellation pain', 0.2),
    s('missed_calls', 'Missed inquiry calls', 0.2),
    s('membership_churn', 'Membership/client churn', 0.15),
    s('staff_scheduling', 'Staff/instructor scheduling burden', 0.15),
  ],
  buying: [
    s('active_memberships', 'Active memberships/clients', 0.3),
    s('high_reviews', 'Many reviews/ratings', 0.25),
    s('multiple_staff', 'Multiple practitioners/instructors', 0.25),
    s('retention_signals', 'Retention/rebooking signals', 0.2),
  ],
  ai: [
    s('ai_frontdesk', 'AI front-desk / intake agent', 0.3),
    s('no_show_reduction', 'AI no-show reduction & recall', 0.2),
    s('intake_automation', 'Intake & consent automation', 0.2),
    s('followup_automation_hw', 'Client follow-up & retention', 0.3),
  ],
  web: [
    s('outdated_site_hw', 'Outdated/low-converting website', 0.35),
    s('no_online_sched', 'No online scheduling', 0.35),
    s('weak_landing', 'Weak landing/conversion pages', 0.3),
  ],
  automation: [
    s('manual_scheduling', 'Manual scheduling & reminders', 0.3),
    s('paper_intake', 'Paper intake forms', 0.25),
    s('no_crm_hw', 'No CRM / client tracking', 0.25),
    s('manual_billing', 'Manual billing/packages', 0.2),
  ],
  app: [
    s('client_portal', 'Client portal / booking app', 0.35),
    s('staff_app', 'Staff scheduling app', 0.3),
    s('wellness_app', 'Wellness/program tracking app', 0.35),
  ],
};

const PROFESSIONAL_SERVICES_SIGNALS = {
  pain: [
    s('manual_intake', 'Manual intake & document handling', 0.3),
    s('slow_response', 'Slow client response / follow-up', 0.25),
    s('no_lead_system', 'No structured lead pipeline', 0.25),
    s('admin_burden', 'Admin/paralegal burden', 0.2),
  ],
  buying: [
    s('team_size', 'Team size (billable headcount)', 0.3),
    s('client_volume', 'High client/case volume', 0.25),
    s('compliance_needs', 'Compliance & record-keeping needs', 0.2),
    s('reputation_signals', 'Reputation/referral signals', 0.25),
  ],
  ai: [
    s('ai_intake', 'AI client intake & triage', 0.3),
    s('doc_automation', 'Document/contract automation', 0.25),
    s('ai_ops', 'AI admin/ops assistant', 0.2),
    s('lead_followup_pro', 'Lead follow-up automation', 0.25),
  ],
  web: [
    s('outdated_site_pro', 'Outdated/low-converting website', 0.4),
    s('no_booking_pro', 'No online consultation booking', 0.3),
    s('no_lead_capture_pro', 'No lead capture/nurture', 0.3),
  ],
  automation: [
    s('manual_forms', 'Manual forms & document assembly', 0.3),
    s('no_crm_pro', 'No CRM / spreadsheet tracking', 0.3),
    s('manual_reminders', 'Manual reminders & follow-up', 0.2),
    s('reporting_manual', 'Manual reporting', 0.2),
  ],
  app: [
    s('client_portal_pro', 'Client portal / case tracker', 0.35),
    s('practice_tool', 'Internal practice tool', 0.3),
    s('document_app', 'Document/approval app', 0.35),
  ],
};

const LOCAL_SERVICES_SIGNALS = {
  pain: [
    s('phone_demand', 'Phone/order-heavy operation', 0.3),
    s('no_online_ordering', 'No online ordering/reservation', 0.25),
    s('manual_scheduling_local', 'Manual scheduling', 0.2),
    s('missed_revenue', 'Missed-call revenue leakage', 0.25),
  ],
  buying: [
    s('foot_traffic', 'Foot traffic / repeat clientele', 0.25),
    s('review_density', 'High review density', 0.25),
    s('multi_branch', 'Multi-branch/vehicle fleet', 0.25),
    s('premium_position', 'Premium local positioning', 0.25),
  ],
  ai: [
    s('ai_reception_local', 'AI receptionist / missed-call recovery', 0.3),
    s('order_assist', 'AI order/quote assist', 0.25),
    s('review_reply_ai', 'Review response automation', 0.2),
    s('followup_local', 'Follow-up & rebooking automation', 0.25),
  ],
  web: [
    s('outdated_site_local', 'Outdated/no website', 0.4),
    s('no_ordering', 'No online ordering/reservations', 0.3),
    s('no_local_seo', 'Weak local SEO/maps presence', 0.3),
  ],
  automation: [
    s('manual_orders', 'Manual order intake', 0.3),
    s('no_pos_integration', 'No booking/CRM integration', 0.3),
    s('manual_staff_sched', 'Manual staff scheduling', 0.2),
    s('no_followup', 'No systematic follow-up', 0.2),
  ],
  app: [
    s('ordering_app', 'Ordering/reservation app', 0.35),
    s('loyalty_app', 'Loyalty/rewards app', 0.3),
    s('staff_tool', 'Staff ops tool', 0.35),
  ],
};

const B2B_INDUSTRIAL_SIGNALS = {
  pain: [
    s('manual_quoting', 'Manual quoting/RFQ handling', 0.3),
    s('no_lead_pipeline', 'No structured sales pipeline', 0.25),
    s('admin_overhead', 'Admin/back-office overhead', 0.2),
    s('slow_fulfillment', 'Slow fulfillment/order tracking', 0.25),
  ],
  buying: [
    s('revenue_scale', 'Revenue/order scale', 0.3),
    s('headcount', 'Headcount / facility footprint', 0.25),
    s('repeat_contracts', 'Repeat/long-term contracts', 0.25),
    s('compliance_reg', 'Compliance/regulatory reporting', 0.2),
  ],
  ai: [
    s('ai_sales_agent', 'AI sales/BDR agent', 0.3),
    s('quote_automation', 'AI quote/estimate automation', 0.25),
    s('ai_support', 'AI customer-support agent', 0.25),
    s('supply_automation', 'Supply-chain/workflow automation', 0.2),
  ],
  web: [
    s('outdated_site_b2b', 'Outdated/no web presence', 0.4),
    s('no_catalog', 'No online catalog/portal', 0.3),
    s('no_lead_capture_b2b', 'No lead capture', 0.3),
  ],
  automation: [
    s('manual_rfq', 'Manual RFQ/quoting', 0.3),
    s('no_erp_crm', 'No CRM/ERP integration', 0.3),
    s('paper_ops', 'Paper-heavy operations', 0.2),
    s('manual_reporting', 'Manual reporting', 0.2),
  ],
  app: [
    s('b2b_portal', 'Customer/supplier portal', 0.35),
    s('ops_app', 'Operations mobile app', 0.3),
    s('contech_tool', 'ConTech/engineering tool', 0.35),
  ],
};

// ── Category → vertical factory ────────────────────────────────────

function v(
  def: Omit<VerticalDefinition, 'category'> & { category: VerticalCategoryId },
): VerticalDefinition {
  return def;
}

const HOME_SERVICES: VerticalDefinition[] = [
  v({
    id: 'hvac', name: 'HVAC & Air Conditioning', category: 'HOME_SERVICES',
    icp: 'Residential/commercial HVAC contractors with 3+ techs, service & install revenue, and emergency call demand.',
    decisionMakerProfile: 'Owner or Service Manager who owns dispatch and booking.',
    painSignals: HOME_SERVICE_SIGNALS.pain,
    buyingSignals: HOME_SERVICE_SIGNALS.buying,
    aiOpportunitySignals: HOME_SERVICE_SIGNALS.ai,
    websiteOpportunitySignals: HOME_SERVICE_SIGNALS.web,
    automationOpportunitySignals: HOME_SERVICE_SIGNALS.automation,
    appSoftwareOpportunitySignals: HOME_SERVICE_SIGNALS.app,
    recommendedOffers: ['AI voice receptionist', 'missed-call recovery', 'appointment automation', 'custom website'],
    estimatedDealSize: { min: 4997, max: 15000, currency: 'USD', unit: 'monthly retainer' },
    outreachAngle: 'Every after-hours AC emergency call currently goes to voicemail — an AI receptionist books them instantly.',
  }),
  v({
    id: 'plumbing', name: 'Plumbing', category: 'HOME_SERVICES',
    icp: 'Plumbing contractors with service/emergency lines and technician dispatch.',
    decisionMakerProfile: 'Owner or Office Manager handling calls and scheduling.',
    painSignals: HOME_SERVICE_SIGNALS.pain,
    buyingSignals: HOME_SERVICE_SIGNALS.buying,
    aiOpportunitySignals: HOME_SERVICE_SIGNALS.ai,
    websiteOpportunitySignals: HOME_SERVICE_SIGNALS.web,
    automationOpportunitySignals: HOME_SERVICE_SIGNALS.automation,
    appSoftwareOpportunitySignals: HOME_SERVICE_SIGNALS.app,
    recommendedOffers: ['missed-call recovery', 'AI voice receptionist', 'dispatch automation', 'booking app'],
    estimatedDealSize: { min: 4997, max: 12000, currency: 'USD', unit: 'monthly retainer' },
    outreachAngle: 'Plumbing is 90% emergencies — an AI dispatcher answers instantly, triages, and schedules the nearest tech.',
  }),
  v({
    id: 'electrical', name: 'Electrical', category: 'HOME_SERVICES',
    icp: 'Electrical contractors with licensed electricians and service/panel upgrade demand.',
    decisionMakerProfile: 'Owner/Master Electrician managing quotes and jobs.',
    painSignals: HOME_SERVICE_SIGNALS.pain,
    buyingSignals: HOME_SERVICE_SIGNALS.buying,
    aiOpportunitySignals: HOME_SERVICE_SIGNALS.ai,
    websiteOpportunitySignals: HOME_SERVICE_SIGNALS.web,
    automationOpportunitySignals: HOME_SERVICE_SIGNALS.automation,
    appSoftwareOpportunitySignals: HOME_SERVICE_SIGNALS.app,
    recommendedOffers: ['AI voice receptionist', 'estimate assist', 'custom website', 'field app'],
    estimatedDealSize: { min: 4997, max: 12000, currency: 'USD', unit: 'monthly retainer' },
    outreachAngle: 'Quote-to-job follow-up is usually manual — automated follow-up + AI estimate assist recovers lost jobs.',
  }),
  v({
    id: 'roofing', name: 'Roofing', category: 'HOME_SERVICES',
    icp: 'Roofing contractors with storm-damage demand, insurance claim workflows, and crews.',
    decisionMakerProfile: 'Owner or Sales Manager who sources jobs and crews.',
    painSignals: HOME_SERVICE_SIGNALS.pain,
    buyingSignals: HOME_SERVICE_SIGNALS.buying,
    aiOpportunitySignals: HOME_SERVICE_SIGNALS.ai,
    websiteOpportunitySignals: HOME_SERVICE_SIGNALS.web,
    automationOpportunitySignals: HOME_SERVICE_SIGNALS.automation,
    appSoftwareOpportunitySignals: HOME_SERVICE_SIGNALS.app,
    recommendedOffers: ['AI voice receptionist', 'lead follow-up', 'claim-intake automation', 'custom website'],
    estimatedDealSize: { min: 5997, max: 18000, currency: 'USD', unit: 'monthly retainer' },
    outreachAngle: 'Storm season floods the phones; an AI intake agent captures every claim lead before competitors do.',
  }),
  v({
    id: 'solar', name: 'Solar', category: 'HOME_SERVICES',
    icp: 'Solar installers/EPCs with quotes, permits, and crews.',
    decisionMakerProfile: 'Owner or Sales Director running the quote pipeline.',
    painSignals: HOME_SERVICE_SIGNALS.pain,
    buyingSignals: HOME_SERVICE_SIGNALS.buying,
    aiOpportunitySignals: HOME_SERVICE_SIGNALS.ai,
    websiteOpportunitySignals: HOME_SERVICE_SIGNALS.web,
    automationOpportunitySignals: HOME_SERVICE_SIGNALS.automation,
    appSoftwareOpportunitySignals: HOME_SERVICE_SIGNALS.app,
    recommendedOffers: ['AI sales agent', 'quote automation', 'lead follow-up', 'custom web app'],
    estimatedDealSize: { min: 5997, max: 20000, currency: 'USD', unit: 'monthly retainer' },
    outreachAngle: 'Solar lives and dies by follow-up speed — an AI sales agent qualifies and books design consults 24/7.',
  }),
  v({
    id: 'landscaping', name: 'Landscaping & Lawn Care', category: 'HOME_SERVICES',
    icp: 'Landscape/lawn companies with recurring maintenance routes and seasonal crews.',
    decisionMakerProfile: 'Owner or Operations Manager scheduling crews.',
    painSignals: HOME_SERVICE_SIGNALS.pain,
    buyingSignals: HOME_SERVICE_SIGNALS.buying,
    aiOpportunitySignals: HOME_SERVICE_SIGNALS.ai,
    websiteOpportunitySignals: HOME_SERVICE_SIGNALS.web,
    automationOpportunitySignals: HOME_SERVICE_SIGNALS.automation,
    appSoftwareOpportunitySignals: HOME_SERVICE_SIGNALS.app,
    recommendedOffers: ['appointment automation', 'route/dispatch automation', 'missed-call recovery', 'customer portal'],
    estimatedDealSize: { min: 3997, max: 10000, currency: 'USD', unit: 'monthly retainer' },
    outreachAngle: 'Maintenance customers churn when nobody follows up — automated renewal + AI booking keeps routes full.',
  }),
  v({
    id: 'pest_control', name: 'Pest Control', category: 'HOME_SERVICES',
    icp: 'Pest control operators with recurring service plans and emergency calls.',
    decisionMakerProfile: 'Owner or Service Manager running routes and renewals.',
    painSignals: HOME_SERVICE_SIGNALS.pain,
    buyingSignals: HOME_SERVICE_SIGNALS.buying,
    aiOpportunitySignals: HOME_SERVICE_SIGNALS.ai,
    websiteOpportunitySignals: HOME_SERVICE_SIGNALS.web,
    automationOpportunitySignals: HOME_SERVICE_SIGNALS.automation,
    appSoftwareOpportunitySignals: HOME_SERVICE_SIGNALS.app,
    recommendedOffers: ['AI voice receptionist', 'plan-renewal automation', 'appointment automation', 'custom website'],
    estimatedDealSize: { min: 3997, max: 10000, currency: 'USD', unit: 'monthly retainer' },
    outreachAngle: 'Pest service plans renew by reminder — automated renewal + AI intake locks in recurring revenue.',
  }),
  v({
    id: 'cleaning', name: 'Commercial & Residential Cleaning', category: 'HOME_SERVICES',
    icp: 'Cleaning companies with residential routes or commercial contracts and staff turnover.',
    decisionMakerProfile: 'Owner or Operations Manager staffing jobs.',
    painSignals: HOME_SERVICE_SIGNALS.pain,
    buyingSignals: HOME_SERVICE_SIGNALS.buying,
    aiOpportunitySignals: HOME_SERVICE_SIGNALS.ai,
    websiteOpportunitySignals: HOME_SERVICE_SIGNALS.web,
    automationOpportunitySignals: HOME_SERVICE_SIGNALS.automation,
    appSoftwareOpportunitySignals: HOME_SERVICE_SIGNALS.app,
    recommendedOffers: ['AI voice receptionist', 'quote automation', 'staff scheduling', 'customer portal'],
    estimatedDealSize: { min: 3997, max: 10000, currency: 'USD', unit: 'monthly retainer' },
    outreachAngle: 'Quotes and recurring cleanings fall through cracks — AI intake + automated scheduling fills the calendar.',
  }),
  v({
    id: 'restoration', name: 'Restoration & Water/Fire Damage', category: 'HOME_SERVICES',
    icp: 'Water/fire/mold restoration companies responding to insurance claims.',
    decisionMakerProfile: 'Owner or Mitigation Manager racing the claim window.',
    painSignals: HOME_SERVICE_SIGNALS.pain,
    buyingSignals: HOME_SERVICE_SIGNALS.buying,
    aiOpportunitySignals: HOME_SERVICE_SIGNALS.ai,
    websiteOpportunitySignals: HOME_SERVICE_SIGNALS.web,
    automationOpportunitySignals: HOME_SERVICE_SIGNALS.automation,
    appSoftwareOpportunitySignals: HOME_SERVICE_SIGNALS.app,
    recommendedOffers: ['missed-call recovery', 'AI voice receptionist', 'claim-intake automation', 'dispatch automation'],
    estimatedDealSize: { min: 5997, max: 20000, currency: 'USD', unit: 'monthly retainer' },
    outreachAngle: 'Restoration is a race — an AI dispatcher answers disaster calls in seconds and routes the mitigation crew.',
  }),
  v({
    id: 'garage_door', name: 'Garage Door Services', category: 'HOME_SERVICES',
    icp: 'Garage door install/repair companies with residential call volume.',
    decisionMakerProfile: 'Owner or Tech/Scheduler.',
    painSignals: HOME_SERVICE_SIGNALS.pain,
    buyingSignals: HOME_SERVICE_SIGNALS.buying,
    aiOpportunitySignals: HOME_SERVICE_SIGNALS.ai,
    websiteOpportunitySignals: HOME_SERVICE_SIGNALS.web,
    automationOpportunitySignals: HOME_SERVICE_SIGNALS.automation,
    appSoftwareOpportunitySignals: HOME_SERVICE_SIGNALS.app,
    recommendedOffers: ['AI voice receptionist', 'missed-call recovery', 'appointment automation', 'custom website'],
    estimatedDealSize: { min: 3997, max: 8000, currency: 'USD', unit: 'monthly retainer' },
    outreachAngle: 'Garage door calls are quick-turn emergencies — AI books service windows instantly.',
  }),
  v({
    id: 'pool_services', name: 'Pool Services', category: 'HOME_SERVICES',
    icp: 'Pool maintenance/repair companies with recurring route clients.',
    decisionMakerProfile: 'Owner or Route Manager.',
    painSignals: HOME_SERVICE_SIGNALS.pain,
    buyingSignals: HOME_SERVICE_SIGNALS.buying,
    aiOpportunitySignals: HOME_SERVICE_SIGNALS.ai,
    websiteOpportunitySignals: HOME_SERVICE_SIGNALS.web,
    automationOpportunitySignals: HOME_SERVICE_SIGNALS.automation,
    appSoftwareOpportunitySignals: HOME_SERVICE_SIGNALS.app,
    recommendedOffers: ['appointment automation', 'route/dispatch automation', 'AI voice receptionist', 'customer portal'],
    estimatedDealSize: { min: 2997, max: 8000, currency: 'USD', unit: 'monthly retainer' },
    outreachAngle: 'Recurring pool routes need zero-friction scheduling — automated booking keeps every slot full.',
  }),
  v({
    id: 'painting', name: 'Painting Contractors', category: 'HOME_SERVICES',
    icp: 'Residential/commercial painting companies with crews and estimates.',
    decisionMakerProfile: 'Owner or Estimator.',
    painSignals: HOME_SERVICE_SIGNALS.pain,
    buyingSignals: HOME_SERVICE_SIGNALS.buying,
    aiOpportunitySignals: HOME_SERVICE_SIGNALS.ai,
    websiteOpportunitySignals: HOME_SERVICE_SIGNALS.web,
    automationOpportunitySignals: HOME_SERVICE_SIGNALS.automation,
    appSoftwareOpportunitySignals: HOME_SERVICE_SIGNALS.app,
    recommendedOffers: ['AI voice receptionist', 'estimate assist', 'lead follow-up', 'custom website'],
    estimatedDealSize: { min: 3997, max: 10000, currency: 'USD', unit: 'monthly retainer' },
    outreachAngle: 'Painting quotes go cold fast — AI follow-up converts estimates into booked crews.',
  }),
  v({
    id: 'flooring', name: 'Flooring & Floor Covering', category: 'HOME_SERVICES',
    icp: 'Flooring retailers/installers with showrooms and measurement appointments.',
    decisionMakerProfile: 'Owner or Sales/Showroom Manager.',
    painSignals: HOME_SERVICE_SIGNALS.pain,
    buyingSignals: HOME_SERVICE_SIGNALS.buying,
    aiOpportunitySignals: HOME_SERVICE_SIGNALS.ai,
    websiteOpportunitySignals: HOME_SERVICE_SIGNALS.web,
    automationOpportunitySignals: HOME_SERVICE_SIGNALS.automation,
    appSoftwareOpportunitySignals: HOME_SERVICE_SIGNALS.app,
    recommendedOffers: ['AI voice receptionist', 'appointment automation', 'lead follow-up', 'custom website'],
    estimatedDealSize: { min: 3997, max: 10000, currency: 'USD', unit: 'monthly retainer' },
    outreachAngle: 'Measure appointments drive flooring sales — AI books them around the clock.',
  }),
  v({
    id: 'remodeling', name: 'Remodeling & Home Improvement', category: 'HOME_SERVICES',
    icp: 'Remodeling contractors with design/estimate pipelines and crews.',
    decisionMakerProfile: 'Owner or Design/Sales Consultant.',
    painSignals: HOME_SERVICE_SIGNALS.pain,
    buyingSignals: HOME_SERVICE_SIGNALS.buying,
    aiOpportunitySignals: HOME_SERVICE_SIGNALS.ai,
    websiteOpportunitySignals: HOME_SERVICE_SIGNALS.web,
    automationOpportunitySignals: HOME_SERVICE_SIGNALS.automation,
    appSoftwareOpportunitySignals: HOME_SERVICE_SIGNALS.app,
    recommendedOffers: ['AI sales agent', 'estimate automation', 'lead follow-up', 'client portal'],
    estimatedDealSize: { min: 5997, max: 18000, currency: 'USD', unit: 'monthly retainer' },
    outreachAngle: 'Big-ticket remodels need fast, persistent follow-up — an AI sales agent keeps every lead warm.',
  }),
  v({
    id: 'general_contractors', name: 'General Contractors', category: 'HOME_SERVICES',
    icp: 'GCs managing residential/commercial projects with bid pipelines and subs.',
    decisionMakerProfile: 'Owner or Project Manager.',
    painSignals: HOME_SERVICE_SIGNALS.pain,
    buyingSignals: HOME_SERVICE_SIGNALS.buying,
    aiOpportunitySignals: HOME_SERVICE_SIGNALS.ai,
    websiteOpportunitySignals: HOME_SERVICE_SIGNALS.web,
    automationOpportunitySignals: HOME_SERVICE_SIGNALS.automation,
    appSoftwareOpportunitySignals: HOME_SERVICE_SIGNALS.app,
    recommendedOffers: ['AI sales agent', 'bid/estimate automation', 'project portal', 'ConTech software'],
    estimatedDealSize: { min: 5997, max: 25000, currency: 'USD', unit: 'monthly retainer' },
    outreachAngle: 'Bids win on speed — AI-backed estimating and follow-up grows your close rate.',
  }),
];

const HEALTH_WELLNESS: VerticalDefinition[] = [
  v({
    id: 'yoga', name: 'Yoga Studios', category: 'HEALTH_WELLNESS',
    icp: 'Yoga studios with class packages, memberships, and multiple instructors.',
    decisionMakerProfile: 'Studio Owner or Manager.',
    painSignals: HEALTH_WELLNESS_SIGNALS.pain,
    buyingSignals: HEALTH_WELLNESS_SIGNALS.buying,
    aiOpportunitySignals: HEALTH_WELLNESS_SIGNALS.ai,
    websiteOpportunitySignals: HEALTH_WELLNESS_SIGNALS.web,
    automationOpportunitySignals: HEALTH_WELLNESS_SIGNALS.automation,
    appSoftwareOpportunitySignals: HEALTH_WELLNESS_SIGNALS.app,
    recommendedOffers: ['appointment automation', 'AI front-desk', 'client portal', 'no-show reduction'],
    estimatedDealSize: { min: 2997, max: 8000, currency: 'USD', unit: 'monthly retainer' },
    outreachAngle: 'Class spots and memberships churn without booking automation — AI keeps classes full.',
  }),
  v({
    id: 'pilates', name: 'Pilates Studios', category: 'HEALTH_WELLNESS',
    icp: 'Pilates studios with reformer capacity, memberships, and instructor teams.',
    decisionMakerProfile: 'Studio Owner or Manager.',
    painSignals: HEALTH_WELLNESS_SIGNALS.pain,
    buyingSignals: HEALTH_WELLNESS_SIGNALS.buying,
    aiOpportunitySignals: HEALTH_WELLNESS_SIGNALS.ai,
    websiteOpportunitySignals: HEALTH_WELLNESS_SIGNALS.web,
    automationOpportunitySignals: HEALTH_WELLNESS_SIGNALS.automation,
    appSoftwareOpportunitySignals: HEALTH_WELLNESS_SIGNALS.app,
    recommendedOffers: ['appointment automation', 'AI front-desk', 'client portal', 'staff scheduling'],
    estimatedDealSize: { min: 2997, max: 8000, currency: 'USD', unit: 'monthly retainer' },
    outreachAngle: 'Pilates sells by the session and the month — AI booking maximizes reformer utilization.',
  }),
  v({
    id: 'gyms', name: 'Gyms & Fitness Centers', category: 'HEALTH_WELLNESS',
    icp: 'Gyms/fitness centers with memberships, classes, and PT revenue.',
    decisionMakerProfile: 'Owner or General Manager.',
    painSignals: HEALTH_WELLNESS_SIGNALS.pain,
    buyingSignals: HEALTH_WELLNESS_SIGNALS.buying,
    aiOpportunitySignals: HEALTH_WELLNESS_SIGNALS.ai,
    websiteOpportunitySignals: HEALTH_WELLNESS_SIGNALS.web,
    automationOpportunitySignals: HEALTH_WELLNESS_SIGNALS.automation,
    appSoftwareOpportunitySignals: HEALTH_WELLNESS_SIGNALS.app,
    recommendedOffers: ['AI front-desk', 'member follow-up', 'appointment automation', 'member app'],
    estimatedDealSize: { min: 4997, max: 15000, currency: 'USD', unit: 'monthly retainer' },
    outreachAngle: 'Membership sales and renewals scale with AI follow-up — never let a trial expire cold.',
  }),
  v({
    id: 'personal_training', name: 'Personal Training', category: 'HEALTH_WELLNESS',
    icp: 'PT studios/trainers with packages and session-based revenue.',
    decisionMakerProfile: 'Owner or Head Trainer.',
    painSignals: HEALTH_WELLNESS_SIGNALS.pain,
    buyingSignals: HEALTH_WELLNESS_SIGNALS.buying,
    aiOpportunitySignals: HEALTH_WELLNESS_SIGNALS.ai,
    websiteOpportunitySignals: HEALTH_WELLNESS_SIGNALS.web,
    automationOpportunitySignals: HEALTH_WELLNESS_SIGNALS.automation,
    appSoftwareOpportunitySignals: HEALTH_WELLNESS_SIGNALS.app,
    recommendedOffers: ['appointment automation', 'no-show reduction', 'client follow-up', 'client app'],
    estimatedDealSize: { min: 2997, max: 8000, currency: 'USD', unit: 'monthly retainer' },
    outreachAngle: 'PT revenue is session and package based — AI booking and recall fill gaps and cut no-shows.',
  }),
  v({
    id: 'med_spas', name: 'Med Spas', category: 'HEALTH_WELLNESS',
    icp: 'Med spas/aesthetic clinics with high-ticket treatments and consult pipelines.',
    decisionMakerProfile: 'Owner or Practice Manager.',
    painSignals: HEALTH_WELLNESS_SIGNALS.pain,
    buyingSignals: HEALTH_WELLNESS_SIGNALS.buying,
    aiOpportunitySignals: HEALTH_WELLNESS_SIGNALS.ai,
    websiteOpportunitySignals: HEALTH_WELLNESS_SIGNALS.web,
    automationOpportunitySignals: HEALTH_WELLNESS_SIGNALS.automation,
    appSoftwareOpportunitySignals: HEALTH_WELLNESS_SIGNALS.app,
    recommendedOffers: ['AI front-desk', 'consult scheduling', 'client follow-up', 'custom website'],
    estimatedDealSize: { min: 5997, max: 15000, currency: 'USD', unit: 'monthly retainer' },
    outreachAngle: 'Med-spa consults are high value — AI books and follows up so no lead ghosts a $2k treatment.',
  }),
  v({
    id: 'chiropractors', name: 'Chiropractors', category: 'HEALTH_WELLNESS',
    icp: 'Chiropractic clinics with recurring care plans and insurance billing.',
    decisionMakerProfile: 'Owner/Doctor or Front Office Manager.',
    painSignals: HEALTH_WELLNESS_SIGNALS.pain,
    buyingSignals: HEALTH_WELLNESS_SIGNALS.buying,
    aiOpportunitySignals: HEALTH_WELLNESS_SIGNALS.ai,
    websiteOpportunitySignals: HEALTH_WELLNESS_SIGNALS.web,
    automationOpportunitySignals: HEALTH_WELLNESS_SIGNALS.automation,
    appSoftwareOpportunitySignals: HEALTH_WELLNESS_SIGNALS.app,
    recommendedOffers: ['AI front-desk', 'appointment automation', 'no-show reduction', 'intake automation'],
    estimatedDealSize: { min: 4997, max: 12000, currency: 'USD', unit: 'monthly retainer' },
    outreachAngle: 'Care plans depend on consistent rebooking — AI recall and no-show reduction protect the schedule.',
  }),
  v({
    id: 'physical_therapy', name: 'Physical Therapy', category: 'HEALTH_WELLNESS',
    icp: 'PT clinics with recurring appointments, insurance referrals, and multiple clinicians.',
    decisionMakerProfile: 'Owner/Clinic Director or Front Office Manager.',
    painSignals: HEALTH_WELLNESS_SIGNALS.pain,
    buyingSignals: HEALTH_WELLNESS_SIGNALS.buying,
    aiOpportunitySignals: HEALTH_WELLNESS_SIGNALS.ai,
    websiteOpportunitySignals: HEALTH_WELLNESS_SIGNALS.web,
    automationOpportunitySignals: HEALTH_WELLNESS_SIGNALS.automation,
    appSoftwareOpportunitySignals: HEALTH_WELLNESS_SIGNALS.app,
    recommendedOffers: ['AI front-desk', 'appointment automation', 'no-show reduction', 'intake automation'],
    estimatedDealSize: { min: 4997, max: 12000, currency: 'USD', unit: 'monthly retainer' },
    outreachAngle: 'PT outcomes depend on attendance — AI rebooking and recall cut no-shows and protect revenue.',
  }),
  v({
    id: 'dental', name: 'Dental Practices', category: 'HEALTH_WELLNESS',
    icp: 'Dental offices with hygiene appointments, recall, and new-patient pipelines.',
    decisionMakerProfile: 'Owner/Dentist or Office Manager.',
    painSignals: HEALTH_WELLNESS_SIGNALS.pain,
    buyingSignals: HEALTH_WELLNESS_SIGNALS.buying,
    aiOpportunitySignals: HEALTH_WELLNESS_SIGNALS.ai,
    websiteOpportunitySignals: HEALTH_WELLNESS_SIGNALS.web,
    automationOpportunitySignals: HEALTH_WELLNESS_SIGNALS.automation,
    appSoftwareOpportunitySignals: HEALTH_WELLNESS_SIGNALS.app,
    recommendedOffers: ['AI front-desk', 'appointment automation', 'recall automation', 'custom website'],
    estimatedDealSize: { min: 4997, max: 15000, currency: 'USD', unit: 'monthly retainer' },
    outreachAngle: 'Dental revenue is appointment-driven — AI recall and booking fill hygiene chairs automatically.',
  }),
  v({
    id: 'aesthetic_clinics', name: 'Aesthetic Clinics', category: 'HEALTH_WELLNESS',
    icp: 'Aesthetic/cosmetic clinics with consult-led treatment sales.',
    decisionMakerProfile: 'Owner or Practice Manager.',
    painSignals: HEALTH_WELLNESS_SIGNALS.pain,
    buyingSignals: HEALTH_WELLNESS_SIGNALS.buying,
    aiOpportunitySignals: HEALTH_WELLNESS_SIGNALS.ai,
    websiteOpportunitySignals: HEALTH_WELLNESS_SIGNALS.web,
    automationOpportunitySignals: HEALTH_WELLNESS_SIGNALS.automation,
    appSoftwareOpportunitySignals: HEALTH_WELLNESS_SIGNALS.app,
    recommendedOffers: ['AI front-desk', 'consult scheduling', 'lead follow-up', 'custom website'],
    estimatedDealSize: { min: 5997, max: 15000, currency: 'USD', unit: 'monthly retainer' },
    outreachAngle: 'Aesthetic consults convert on speed and follow-up — an AI front-desk books and nurtures them.',
  }),
  v({
    id: 'massage', name: 'Massage Therapy', category: 'HEALTH_WELLNESS',
    icp: 'Massage practices with session-based revenue and memberships.',
    decisionMakerProfile: 'Owner or Lead Therapist.',
    painSignals: HEALTH_WELLNESS_SIGNALS.pain,
    buyingSignals: HEALTH_WELLNESS_SIGNALS.buying,
    aiOpportunitySignals: HEALTH_WELLNESS_SIGNALS.ai,
    websiteOpportunitySignals: HEALTH_WELLNESS_SIGNALS.web,
    automationOpportunitySignals: HEALTH_WELLNESS_SIGNALS.automation,
    appSoftwareOpportunitySignals: HEALTH_WELLNESS_SIGNALS.app,
    recommendedOffers: ['appointment automation', 'no-show reduction', 'client follow-up', 'client app'],
    estimatedDealSize: { min: 2997, max: 8000, currency: 'USD', unit: 'monthly retainer' },
    outreachAngle: 'Massage books by appointment — AI scheduling and recall fill the book and cut no-shows.',
  }),
  v({
    id: 'wellness', name: 'Wellness & Holistic Centers', category: 'HEALTH_WELLNESS',
    icp: 'Wellness centers offering mixed services (acupuncture, coaching, etc.) with packages.',
    decisionMakerProfile: 'Owner or Center Manager.',
    painSignals: HEALTH_WELLNESS_SIGNALS.pain,
    buyingSignals: HEALTH_WELLNESS_SIGNALS.buying,
    aiOpportunitySignals: HEALTH_WELLNESS_SIGNALS.ai,
    websiteOpportunitySignals: HEALTH_WELLNESS_SIGNALS.web,
    automationOpportunitySignals: HEALTH_WELLNESS_SIGNALS.automation,
    appSoftwareOpportunitySignals: HEALTH_WELLNESS_SIGNALS.app,
    recommendedOffers: ['AI front-desk', 'appointment automation', 'client follow-up', 'wellness app'],
    estimatedDealSize: { min: 2997, max: 8000, currency: 'USD', unit: 'monthly retainer' },
    outreachAngle: 'Multi-service wellness runs on bookings — AI intake routes clients to the right provider.',
  }),
  v({
    id: 'nutrition', name: 'Nutrition & Dietetics', category: 'HEALTH_WELLNESS',
    icp: 'Nutritionists/dietitians with consult packages and program clients.',
    decisionMakerProfile: 'Owner/Practitioner.',
    painSignals: HEALTH_WELLNESS_SIGNALS.pain,
    buyingSignals: HEALTH_WELLNESS_SIGNALS.buying,
    aiOpportunitySignals: HEALTH_WELLNESS_SIGNALS.ai,
    websiteOpportunitySignals: HEALTH_WELLNESS_SIGNALS.web,
    automationOpportunitySignals: HEALTH_WELLNESS_SIGNALS.automation,
    appSoftwareOpportunitySignals: HEALTH_WELLNESS_SIGNALS.app,
    recommendedOffers: ['appointment automation', 'client follow-up', 'intake automation', 'client app'],
    estimatedDealSize: { min: 2997, max: 8000, currency: 'USD', unit: 'monthly retainer' },
    outreachAngle: 'Nutrition programs need engagement — automated check-ins and booking keep clients on track.',
  }),
];

const PROFESSIONAL_SERVICES: VerticalDefinition[] = [
  v({
    id: 'law_firms', name: 'Law Firms', category: 'PROFESSIONAL_SERVICES',
    icp: 'Small/mid law firms with intake-led case volume.',
    decisionMakerProfile: 'Managing Partner or Intake Manager.',
    painSignals: PROFESSIONAL_SERVICES_SIGNALS.pain,
    buyingSignals: PROFESSIONAL_SERVICES_SIGNALS.buying,
    aiOpportunitySignals: PROFESSIONAL_SERVICES_SIGNALS.ai,
    websiteOpportunitySignals: PROFESSIONAL_SERVICES_SIGNALS.web,
    automationOpportunitySignals: PROFESSIONAL_SERVICES_SIGNALS.automation,
    appSoftwareOpportunitySignals: PROFESSIONAL_SERVICES_SIGNALS.app,
    recommendedOffers: ['AI intake/triage', 'document automation', 'lead follow-up', 'client portal'],
    estimatedDealSize: { min: 5997, max: 25000, currency: 'USD', unit: 'monthly retainer' },
    outreachAngle: 'Every missed intake call is a lost case — AI triage captures and routes them instantly.',
  }),
  v({
    id: 'accounting', name: 'Accounting Firms', category: 'PROFESSIONAL_SERVICES',
    icp: 'CPA/accounting firms with tax season volume and client document handling.',
    decisionMakerProfile: 'Managing Partner or Practice Admin.',
    painSignals: PROFESSIONAL_SERVICES_SIGNALS.pain,
    buyingSignals: PROFESSIONAL_SERVICES_SIGNALS.buying,
    aiOpportunitySignals: PROFESSIONAL_SERVICES_SIGNALS.ai,
    websiteOpportunitySignals: PROFESSIONAL_SERVICES_SIGNALS.web,
    automationOpportunitySignals: PROFESSIONAL_SERVICES_SIGNALS.automation,
    appSoftwareOpportunitySignals: PROFESSIONAL_SERVICES_SIGNALS.app,
    recommendedOffers: ['document automation', 'AI admin assistant', 'client portal', 'workflow automation'],
    estimatedDealSize: { min: 4997, max: 20000, currency: 'USD', unit: 'monthly retainer' },
    outreachAngle: 'Tax season drowns staff in documents — automation assembles and routes them for you.',
  }),
  v({
    id: 'tax', name: 'Tax Preparation & Advisory', category: 'PROFESSIONAL_SERVICES',
    icp: 'Tax firms with seasonal intake and document collection.',
    decisionMakerProfile: 'Owner or Office Manager.',
    painSignals: PROFESSIONAL_SERVICES_SIGNALS.pain,
    buyingSignals: PROFESSIONAL_SERVICES_SIGNALS.buying,
    aiOpportunitySignals: PROFESSIONAL_SERVICES_SIGNALS.ai,
    websiteOpportunitySignals: PROFESSIONAL_SERVICES_SIGNALS.web,
    automationOpportunitySignals: PROFESSIONAL_SERVICES_SIGNALS.automation,
    appSoftwareOpportunitySignals: PROFESSIONAL_SERVICES_SIGNALS.app,
    recommendedOffers: ['document automation', 'client intake', 'AI admin assistant', 'client portal'],
    estimatedDealSize: { min: 3997, max: 15000, currency: 'USD', unit: 'monthly retainer' },
    outreachAngle: 'Tax document collection is manual and messy — automated intake cuts turnaround in half.',
  }),
  v({
    id: 'insurance', name: 'Insurance Agencies', category: 'PROFESSIONAL_SERVICES',
    icp: 'Insurance agencies with quote requests and policy renewal follow-up.',
    decisionMakerProfile: 'Owner or Agency Principal.',
    painSignals: PROFESSIONAL_SERVICES_SIGNALS.pain,
    buyingSignals: PROFESSIONAL_SERVICES_SIGNALS.buying,
    aiOpportunitySignals: PROFESSIONAL_SERVICES_SIGNALS.ai,
    websiteOpportunitySignals: PROFESSIONAL_SERVICES_SIGNALS.web,
    automationOpportunitySignals: PROFESSIONAL_SERVICES_SIGNALS.automation,
    appSoftwareOpportunitySignals: PROFESSIONAL_SERVICES_SIGNALS.app,
    recommendedOffers: ['AI voice receptionist', 'quote follow-up', 'policy renewal automation', 'custom website'],
    estimatedDealSize: { min: 4997, max: 15000, currency: 'USD', unit: 'monthly retainer' },
    outreachAngle: 'Quotes go cold in a day — AI follow-up converts and renewals never slip.',
  }),
  v({
    id: 'mortgage', name: 'Mortgage Brokers & Lenders', category: 'PROFESSIONAL_SERVICES',
    icp: 'Mortgage brokers/loan officers with lead-heavy pipelines.',
    decisionMakerProfile: 'Owner or Sales Manager.',
    painSignals: PROFESSIONAL_SERVICES_SIGNALS.pain,
    buyingSignals: PROFESSIONAL_SERVICES_SIGNALS.buying,
    aiOpportunitySignals: PROFESSIONAL_SERVICES_SIGNALS.ai,
    websiteOpportunitySignals: PROFESSIONAL_SERVICES_SIGNALS.web,
    automationOpportunitySignals: PROFESSIONAL_SERVICES_SIGNALS.automation,
    appSoftwareOpportunitySignals: PROFESSIONAL_SERVICES_SIGNALS.app,
    recommendedOffers: ['AI sales agent', 'lead follow-up', 'loan-intake automation', 'custom web app'],
    estimatedDealSize: { min: 4997, max: 20000, currency: 'USD', unit: 'monthly retainer' },
    outreachAngle: 'Borrowers compare lenders in hours — an AI agent pre-qualifies and books LO calls instantly.',
  }),
  v({
    id: 'real_estate_brokerages', name: 'Real Estate Brokerages', category: 'PROFESSIONAL_SERVICES',
    icp: 'Brokerages with agent teams and listing/buyer lead flow.',
    decisionMakerProfile: 'Broker/Owner or Marketing Director.',
    painSignals: PROFESSIONAL_SERVICES_SIGNALS.pain,
    buyingSignals: PROFESSIONAL_SERVICES_SIGNALS.buying,
    aiOpportunitySignals: PROFESSIONAL_SERVICES_SIGNALS.ai,
    websiteOpportunitySignals: PROFESSIONAL_SERVICES_SIGNALS.web,
    automationOpportunitySignals: PROFESSIONAL_SERVICES_SIGNALS.automation,
    appSoftwareOpportunitySignals: PROFESSIONAL_SERVICES_SIGNALS.app,
    recommendedOffers: ['AI sales agent', 'lead follow-up', 'custom website', 'CRM automation'],
    estimatedDealSize: { min: 4997, max: 20000, currency: 'USD', unit: 'monthly retainer' },
    outreachAngle: 'Buyers and sellers expect instant response — AI qualifies and routes leads to agents in seconds.',
  }),
  v({
    id: 'property_management', name: 'Property Management', category: 'PROFESSIONAL_SERVICES',
    icp: 'Property managers with maintenance calls, tenant inquiries, and owner reporting.',
    decisionMakerProfile: 'Owner or Ops Manager.',
    painSignals: PROFESSIONAL_SERVICES_SIGNALS.pain,
    buyingSignals: PROFESSIONAL_SERVICES_SIGNALS.buying,
    aiOpportunitySignals: PROFESSIONAL_SERVICES_SIGNALS.ai,
    websiteOpportunitySignals: PROFESSIONAL_SERVICES_SIGNALS.web,
    automationOpportunitySignals: PROFESSIONAL_SERVICES_SIGNALS.automation,
    appSoftwareOpportunitySignals: PROFESSIONAL_SERVICES_SIGNALS.app,
    recommendedOffers: ['AI voice receptionist', 'maintenance triage', 'tenant portal', 'work-order automation'],
    estimatedDealSize: { min: 4997, max: 15000, currency: 'USD', unit: 'monthly retainer' },
    outreachAngle: 'Maintenance calls pile up after hours — an AI agent triages, dispatches, and logs every ticket.',
  }),
  v({
    id: 'architecture', name: 'Architecture Firms', category: 'PROFESSIONAL_SERVICES',
    icp: 'Architecture firms with proposal pipelines and document-heavy projects.',
    decisionMakerProfile: 'Principal or Business Development lead.',
    painSignals: PROFESSIONAL_SERVICES_SIGNALS.pain,
    buyingSignals: PROFESSIONAL_SERVICES_SIGNALS.buying,
    aiOpportunitySignals: PROFESSIONAL_SERVICES_SIGNALS.ai,
    websiteOpportunitySignals: PROFESSIONAL_SERVICES_SIGNALS.web,
    automationOpportunitySignals: PROFESSIONAL_SERVICES_SIGNALS.automation,
    appSoftwareOpportunitySignals: PROFESSIONAL_SERVICES_SIGNALS.app,
    recommendedOffers: ['ConTech software', 'AI internal tool', 'document automation', 'client portal'],
    estimatedDealSize: { min: 5997, max: 25000, currency: 'USD', unit: 'monthly retainer' },
    outreachAngle: 'Firm growth is bottlenecked by proposals and coordination — automation reclaims billable hours.',
  }),
  v({
    id: 'engineering', name: 'Engineering Firms', category: 'PROFESSIONAL_SERVICES',
    icp: 'Civil/structural/MEP engineering firms with CAD/takeoff-heavy workflows.',
    decisionMakerProfile: 'Principal or Ops Director.',
    painSignals: PROFESSIONAL_SERVICES_SIGNALS.pain,
    buyingSignals: PROFESSIONAL_SERVICES_SIGNALS.buying,
    aiOpportunitySignals: PROFESSIONAL_SERVICES_SIGNALS.ai,
    websiteOpportunitySignals: PROFESSIONAL_SERVICES_SIGNALS.web,
    automationOpportunitySignals: PROFESSIONAL_SERVICES_SIGNALS.automation,
    appSoftwareOpportunitySignals: PROFESSIONAL_SERVICES_SIGNALS.app,
    recommendedOffers: ['ConTech software', 'drawing/takeoff automation', 'AI internal tool', 'workflow automation'],
    estimatedDealSize: { min: 5997, max: 25000, currency: 'USD', unit: 'monthly retainer' },
    outreachAngle: 'Takeoffs and drafting eat margins — ConTech automation accelerates delivery without headcount.',
  }),
  v({
    id: 'construction', name: 'Construction Management', category: 'PROFESSIONAL_SERVICES',
    icp: 'Construction management firms with estimating, scheduling, and reporting burdens.',
    decisionMakerProfile: 'Owner or Chief Estimator.',
    painSignals: PROFESSIONAL_SERVICES_SIGNALS.pain,
    buyingSignals: PROFESSIONAL_SERVICES_SIGNALS.buying,
    aiOpportunitySignals: PROFESSIONAL_SERVICES_SIGNALS.ai,
    websiteOpportunitySignals: PROFESSIONAL_SERVICES_SIGNALS.web,
    automationOpportunitySignals: PROFESSIONAL_SERVICES_SIGNALS.automation,
    appSoftwareOpportunitySignals: PROFESSIONAL_SERVICES_SIGNALS.app,
    recommendedOffers: ['ConTech software', 'estimate automation', 'project portal', 'AI internal tool'],
    estimatedDealSize: { min: 5997, max: 30000, currency: 'USD', unit: 'monthly retainer' },
    outreachAngle: 'Bid speed wins projects — automated estimating and follow-up compound your win rate.',
  }),
];

const LOCAL_SERVICES: VerticalDefinition[] = [
  v({
    id: 'restaurants', name: 'Restaurants', category: 'LOCAL_SERVICES',
    icp: 'Independent restaurants with takeout/delivery volume and reservation needs.',
    decisionMakerProfile: 'Owner or General Manager.',
    painSignals: LOCAL_SERVICES_SIGNALS.pain,
    buyingSignals: LOCAL_SERVICES_SIGNALS.buying,
    aiOpportunitySignals: LOCAL_SERVICES_SIGNALS.ai,
    websiteOpportunitySignals: LOCAL_SERVICES_SIGNALS.web,
    automationOpportunitySignals: LOCAL_SERVICES_SIGNALS.automation,
    appSoftwareOpportunitySignals: LOCAL_SERVICES_SIGNALS.app,
    recommendedOffers: ['AI voice receptionist', 'order assist', 'reservation automation', 'ordering app'],
    estimatedDealSize: { min: 2997, max: 10000, currency: 'USD', unit: 'monthly retainer' },
    outreachAngle: 'Missed calls and slow phone orders leak revenue — an AI agent answers and takes orders.',
  }),
  v({
    id: 'catering', name: 'Catering', category: 'LOCAL_SERVICES',
    icp: 'Catering companies with event quotes and menu/booking requests.',
    decisionMakerProfile: 'Owner or Event Sales Manager.',
    painSignals: LOCAL_SERVICES_SIGNALS.pain,
    buyingSignals: LOCAL_SERVICES_SIGNALS.buying,
    aiOpportunitySignals: LOCAL_SERVICES_SIGNALS.ai,
    websiteOpportunitySignals: LOCAL_SERVICES_SIGNALS.web,
    automationOpportunitySignals: LOCAL_SERVICES_SIGNALS.automation,
    appSoftwareOpportunitySignals: LOCAL_SERVICES_SIGNALS.app,
    recommendedOffers: ['AI voice receptionist', 'quote assist', 'event inquiry automation', 'custom website'],
    estimatedDealSize: { min: 3997, max: 12000, currency: 'USD', unit: 'monthly retainer' },
    outreachAngle: 'Event inquiries demand instant quotes — AI captures specs and books tastings fast.',
  }),
  v({
    id: 'auto_repair', name: 'Auto Repair', category: 'LOCAL_SERVICES',
    icp: 'Independent auto repair shops with service appointments and diagnostics.',
    decisionMakerProfile: 'Owner or Service Advisor.',
    painSignals: LOCAL_SERVICES_SIGNALS.pain,
    buyingSignals: LOCAL_SERVICES_SIGNALS.buying,
    aiOpportunitySignals: LOCAL_SERVICES_SIGNALS.ai,
    websiteOpportunitySignals: LOCAL_SERVICES_SIGNALS.web,
    automationOpportunitySignals: LOCAL_SERVICES_SIGNALS.automation,
    appSoftwareOpportunitySignals: LOCAL_SERVICES_SIGNALS.app,
    recommendedOffers: ['AI voice receptionist', 'appointment automation', 'status updates', 'customer portal'],
    estimatedDealSize: { min: 3997, max: 10000, currency: 'USD', unit: 'monthly retainer' },
    outreachAngle: 'Every appointment phone call is a chance to lose a customer — AI books and updates them automatically.',
  }),
  v({
    id: 'auto_dealers', name: 'Auto Dealers', category: 'LOCAL_SERVICES',
    icp: 'Independent dealers with inventory inquiries and test-drive requests.',
    decisionMakerProfile: 'Owner or Sales Manager.',
    painSignals: LOCAL_SERVICES_SIGNALS.pain,
    buyingSignals: LOCAL_SERVICES_SIGNALS.buying,
    aiOpportunitySignals: LOCAL_SERVICES_SIGNALS.ai,
    websiteOpportunitySignals: LOCAL_SERVICES_SIGNALS.web,
    automationOpportunitySignals: LOCAL_SERVICES_SIGNALS.automation,
    appSoftwareOpportunitySignals: LOCAL_SERVICES_SIGNALS.app,
    recommendedOffers: ['AI sales agent', 'lead follow-up', 'custom website', 'inventory app'],
    estimatedDealSize: { min: 4997, max: 15000, currency: 'USD', unit: 'monthly retainer' },
    outreachAngle: 'Car buyers move fast — an AI agent qualifies inventory interest and books test drives 24/7.',
  }),
  v({
    id: 'detailing', name: 'Detailing & Car Care', category: 'LOCAL_SERVICES',
    icp: 'Auto detailing businesses with appointment-based revenue.',
    decisionMakerProfile: 'Owner or Manager.',
    painSignals: LOCAL_SERVICES_SIGNALS.pain,
    buyingSignals: LOCAL_SERVICES_SIGNALS.buying,
    aiOpportunitySignals: LOCAL_SERVICES_SIGNALS.ai,
    websiteOpportunitySignals: LOCAL_SERVICES_SIGNALS.web,
    automationOpportunitySignals: LOCAL_SERVICES_SIGNALS.automation,
    appSoftwareOpportunitySignals: LOCAL_SERVICES_SIGNALS.app,
    recommendedOffers: ['appointment automation', 'AI voice receptionist', 'no-show reduction', 'booking app'],
    estimatedDealSize: { min: 2997, max: 8000, currency: 'USD', unit: 'monthly retainer' },
    outreachAngle: 'Detailing books by appointment — AI scheduling keeps bays full and cuts no-shows.',
  }),
  v({
    id: 'salons', name: 'Salons', category: 'LOCAL_SERVICES',
    icp: 'Hair salons with appointments, stylist teams, and retail.',
    decisionMakerProfile: 'Owner or Salon Manager.',
    painSignals: LOCAL_SERVICES_SIGNALS.pain,
    buyingSignals: LOCAL_SERVICES_SIGNALS.buying,
    aiOpportunitySignals: LOCAL_SERVICES_SIGNALS.ai,
    websiteOpportunitySignals: LOCAL_SERVICES_SIGNALS.web,
    automationOpportunitySignals: LOCAL_SERVICES_SIGNALS.automation,
    appSoftwareOpportunitySignals: LOCAL_SERVICES_SIGNALS.app,
    recommendedOffers: ['appointment automation', 'AI voice receptionist', 'no-show reduction', 'client app'],
    estimatedDealSize: { min: 2997, max: 8000, currency: 'USD', unit: 'monthly retainer' },
    outreachAngle: 'Stylist chairs earn per hour — AI booking and recall maximize utilization and cut no-shows.',
  }),
  v({
    id: 'barbers', name: 'Barbershops', category: 'LOCAL_SERVICES',
    icp: 'Barbershops with walk-ins/appointments and chair teams.',
    decisionMakerProfile: 'Owner or Shop Manager.',
    painSignals: LOCAL_SERVICES_SIGNALS.pain,
    buyingSignals: LOCAL_SERVICES_SIGNALS.buying,
    aiOpportunitySignals: LOCAL_SERVICES_SIGNALS.ai,
    websiteOpportunitySignals: LOCAL_SERVICES_SIGNALS.web,
    automationOpportunitySignals: LOCAL_SERVICES_SIGNALS.automation,
    appSoftwareOpportunitySignals: LOCAL_SERVICES_SIGNALS.app,
    recommendedOffers: ['appointment automation', 'no-show reduction', 'client follow-up', 'booking app'],
    estimatedDealSize: { min: 1997, max: 6000, currency: 'USD', unit: 'monthly retainer' },
    outreachAngle: 'Barbers lose chairs to no-shows — AI booking and recall keep appointments full.',
  }),
  v({
    id: 'beauty_studios', name: 'Beauty Studios', category: 'LOCAL_SERVICES',
    icp: 'Beauty studios (lash, brow, wax, nails) with high-turnover bookings.',
    decisionMakerProfile: 'Owner or Studio Manager.',
    painSignals: LOCAL_SERVICES_SIGNALS.pain,
    buyingSignals: LOCAL_SERVICES_SIGNALS.buying,
    aiOpportunitySignals: LOCAL_SERVICES_SIGNALS.ai,
    websiteOpportunitySignals: LOCAL_SERVICES_SIGNALS.web,
    automationOpportunitySignals: LOCAL_SERVICES_SIGNALS.automation,
    appSoftwareOpportunitySignals: LOCAL_SERVICES_SIGNALS.app,
    recommendedOffers: ['appointment automation', 'AI front-desk', 'no-show reduction', 'client app'],
    estimatedDealSize: { min: 2997, max: 8000, currency: 'USD', unit: 'monthly retainer' },
    outreachAngle: 'Beauty bookings are high-frequency — AI front-desk and recall keep chairs and books full.',
  }),
  v({
    id: 'pet_grooming', name: 'Pet Grooming', category: 'LOCAL_SERVICES',
    icp: 'Pet grooming businesses with appointment-based revenue.',
    decisionMakerProfile: 'Owner or Grooming Manager.',
    painSignals: LOCAL_SERVICES_SIGNALS.pain,
    buyingSignals: LOCAL_SERVICES_SIGNALS.buying,
    aiOpportunitySignals: LOCAL_SERVICES_SIGNALS.ai,
    websiteOpportunitySignals: LOCAL_SERVICES_SIGNALS.web,
    automationOpportunitySignals: LOCAL_SERVICES_SIGNALS.automation,
    appSoftwareOpportunitySignals: LOCAL_SERVICES_SIGNALS.app,
    recommendedOffers: ['appointment automation', 'AI voice receptionist', 'no-show reduction', 'client portal'],
    estimatedDealSize: { min: 1997, max: 6000, currency: 'USD', unit: 'monthly retainer' },
    outreachAngle: 'Grooming books out by appointment — AI scheduling and reminders cut no-shows.',
  }),
  v({
    id: 'veterinary', name: 'Veterinary Clinics', category: 'LOCAL_SERVICES',
    icp: 'Vet clinics with appointments, emergencies, and recall.',
    decisionMakerProfile: 'Owner/Vet or Practice Manager.',
    painSignals: LOCAL_SERVICES_SIGNALS.pain,
    buyingSignals: LOCAL_SERVICES_SIGNALS.buying,
    aiOpportunitySignals: LOCAL_SERVICES_SIGNALS.ai,
    websiteOpportunitySignals: LOCAL_SERVICES_SIGNALS.web,
    automationOpportunitySignals: LOCAL_SERVICES_SIGNALS.automation,
    appSoftwareOpportunitySignals: LOCAL_SERVICES_SIGNALS.app,
    recommendedOffers: ['AI front-desk', 'appointment automation', 'recall automation', 'intake automation'],
    estimatedDealSize: { min: 3997, max: 12000, currency: 'USD', unit: 'monthly retainer' },
    outreachAngle: 'Pet owners panic-call — an AI front-desk triages emergencies and books visits instantly.',
  }),
  v({
    id: 'moving', name: 'Moving Companies', category: 'LOCAL_SERVICES',
    icp: 'Moving companies with quote requests and seasonal demand.',
    decisionMakerProfile: 'Owner or Dispatch Manager.',
    painSignals: LOCAL_SERVICES_SIGNALS.pain,
    buyingSignals: LOCAL_SERVICES_SIGNALS.buying,
    aiOpportunitySignals: LOCAL_SERVICES_SIGNALS.ai,
    websiteOpportunitySignals: LOCAL_SERVICES_SIGNALS.web,
    automationOpportunitySignals: LOCAL_SERVICES_SIGNALS.automation,
    appSoftwareOpportunitySignals: LOCAL_SERVICES_SIGNALS.app,
    recommendedOffers: ['AI voice receptionist', 'quote assist', 'missed-call recovery', 'dispatch automation'],
    estimatedDealSize: { min: 3997, max: 10000, currency: 'USD', unit: 'monthly retainer' },
    outreachAngle: 'Moves are scheduled on first contact — AI answers, quotes, and books trucks before competitors.',
  }),
  v({
    id: 'storage', name: 'Storage Facilities', category: 'LOCAL_SERVICES',
    icp: 'Self-storage operators with unit inquiries and reservations.',
    decisionMakerProfile: 'Owner or Site Manager.',
    painSignals: LOCAL_SERVICES_SIGNALS.pain,
    buyingSignals: LOCAL_SERVICES_SIGNALS.buying,
    aiOpportunitySignals: LOCAL_SERVICES_SIGNALS.ai,
    websiteOpportunitySignals: LOCAL_SERVICES_SIGNALS.web,
    automationOpportunitySignals: LOCAL_SERVICES_SIGNALS.automation,
    appSoftwareOpportunitySignals: LOCAL_SERVICES_SIGNALS.app,
    recommendedOffers: ['AI voice receptionist', 'unit reservation', 'missed-call recovery', 'customer portal'],
    estimatedDealSize: { min: 2997, max: 8000, currency: 'USD', unit: 'monthly retainer' },
    outreachAngle: 'Storage renters book in one call — AI answers after hours and reserves units automatically.',
  }),
];

const B2B_INDUSTRIAL: VerticalDefinition[] = [
  v({
    id: 'manufacturing', name: 'Manufacturing', category: 'B2B_INDUSTRIAL',
    icp: 'Manufacturers (SMB) with quoting, production scheduling, and back-office overhead.',
    decisionMakerProfile: 'Owner/President or Ops Manager.',
    painSignals: B2B_INDUSTRIAL_SIGNALS.pain,
    buyingSignals: B2B_INDUSTRIAL_SIGNALS.buying,
    aiOpportunitySignals: B2B_INDUSTRIAL_SIGNALS.ai,
    websiteOpportunitySignals: B2B_INDUSTRIAL_SIGNALS.web,
    automationOpportunitySignals: B2B_INDUSTRIAL_SIGNALS.automation,
    appSoftwareOpportunitySignals: B2B_INDUSTRIAL_SIGNALS.app,
    recommendedOffers: ['AI sales agent', 'quote automation', 'workflow automation', 'ops app'],
    estimatedDealSize: { min: 5997, max: 30000, currency: 'USD', unit: 'monthly retainer' },
    outreachAngle: 'RFQs and quotes run on spreadsheets — AI quoting and follow-up accelerate revenue.',
  }),
  v({
    id: 'distributors', name: 'Distributors & Wholesalers', category: 'B2B_INDUSTRIAL',
    icp: 'Distributors with order entry, inventory, and supplier coordination.',
    decisionMakerProfile: 'Owner or Sales/Operations Manager.',
    painSignals: B2B_INDUSTRIAL_SIGNALS.pain,
    buyingSignals: B2B_INDUSTRIAL_SIGNALS.buying,
    aiOpportunitySignals: B2B_INDUSTRIAL_SIGNALS.ai,
    websiteOpportunitySignals: B2B_INDUSTRIAL_SIGNALS.web,
    automationOpportunitySignals: B2B_INDUSTRIAL_SIGNALS.automation,
    appSoftwareOpportunitySignals: B2B_INDUSTRIAL_SIGNALS.app,
    recommendedOffers: ['AI sales agent', 'order automation', 'customer portal', 'supply-chain automation'],
    estimatedDealSize: { min: 5997, max: 25000, currency: 'USD', unit: 'monthly retainer' },
    outreachAngle: 'Order entry and follow-up are manual — automation turns quotes into repeat orders.',
  }),
  v({
    id: 'logistics', name: 'Logistics & Freight', category: 'B2B_INDUSTRIAL',
    icp: 'Freight/logistics SMBs with dispatch, quoting, and tracking workflows.',
    decisionMakerProfile: 'Owner or Dispatch Manager.',
    painSignals: B2B_INDUSTRIAL_SIGNALS.pain,
    buyingSignals: B2B_INDUSTRIAL_SIGNALS.buying,
    aiOpportunitySignals: B2B_INDUSTRIAL_SIGNALS.ai,
    websiteOpportunitySignals: B2B_INDUSTRIAL_SIGNALS.web,
    automationOpportunitySignals: B2B_INDUSTRIAL_SIGNALS.automation,
    appSoftwareOpportunitySignals: B2B_INDUSTRIAL_SIGNALS.app,
    recommendedOffers: ['AI sales agent', 'quote automation', 'dispatch automation', 'customer portal'],
    estimatedDealSize: { min: 5997, max: 25000, currency: 'USD', unit: 'monthly retainer' },
    outreachAngle: 'Freight quotes need speed — AI pricing and follow-up win loads before competitors.',
  }),
  v({
    id: 'staffing', name: 'Staffing & Recruiting', category: 'B2B_INDUSTRIAL',
    icp: 'Staffing agencies with requisition pipelines and candidate follow-up.',
    decisionMakerProfile: 'Owner or Recruiting Director.',
    painSignals: B2B_INDUSTRIAL_SIGNALS.pain,
    buyingSignals: B2B_INDUSTRIAL_SIGNALS.buying,
    aiOpportunitySignals: B2B_INDUSTRIAL_SIGNALS.ai,
    websiteOpportunitySignals: B2B_INDUSTRIAL_SIGNALS.web,
    automationOpportunitySignals: B2B_INDUSTRIAL_SIGNALS.automation,
    appSoftwareOpportunitySignals: B2B_INDUSTRIAL_SIGNALS.app,
    recommendedOffers: ['AI sales agent', 'candidate follow-up', 'intake automation', 'recruiter tool'],
    estimatedDealSize: { min: 4997, max: 20000, currency: 'USD', unit: 'monthly retainer' },
    outreachAngle: 'Every open req is revenue — AI screens and follows up candidates and clients 24/7.',
  }),
  v({
    id: 'commercial_contractors', name: 'Commercial Contractors', category: 'B2B_INDUSTRIAL',
    icp: 'Commercial GCs/subs with bid pipelines and project reporting.',
    decisionMakerProfile: 'Owner or Chief Estimator.',
    painSignals: B2B_INDUSTRIAL_SIGNALS.pain,
    buyingSignals: B2B_INDUSTRIAL_SIGNALS.buying,
    aiOpportunitySignals: B2B_INDUSTRIAL_SIGNALS.ai,
    websiteOpportunitySignals: B2B_INDUSTRIAL_SIGNALS.web,
    automationOpportunitySignals: B2B_INDUSTRIAL_SIGNALS.automation,
    appSoftwareOpportunitySignals: B2B_INDUSTRIAL_SIGNALS.app,
    recommendedOffers: ['ConTech software', 'estimate automation', 'AI internal tool', 'project portal'],
    estimatedDealSize: { min: 5997, max: 30000, currency: 'USD', unit: 'monthly retainer' },
    outreachAngle: 'Bids and project reporting eat margins — ConTech automation wins more, faster.',
  }),
  v({
    id: 'industrial_suppliers', name: 'Industrial Suppliers', category: 'B2B_INDUSTRIAL',
    icp: 'Industrial supply companies with catalog sales and RFQs.',
    decisionMakerProfile: 'Owner or Sales Manager.',
    painSignals: B2B_INDUSTRIAL_SIGNALS.pain,
    buyingSignals: B2B_INDUSTRIAL_SIGNALS.buying,
    aiOpportunitySignals: B2B_INDUSTRIAL_SIGNALS.ai,
    websiteOpportunitySignals: B2B_INDUSTRIAL_SIGNALS.web,
    automationOpportunitySignals: B2B_INDUSTRIAL_SIGNALS.automation,
    appSoftwareOpportunitySignals: B2B_INDUSTRIAL_SIGNALS.app,
    recommendedOffers: ['AI sales agent', 'quote automation', 'customer portal', 'order automation'],
    estimatedDealSize: { min: 5997, max: 25000, currency: 'USD', unit: 'monthly retainer' },
    outreachAngle: 'RFQs hit the inbox and die — AI responds, quotes, and tracks every opportunity.',
  }),
  v({
    id: 'security', name: 'Security & Surveillance', category: 'B2B_INDUSTRIAL',
    icp: 'Security companies with monitoring contracts and installation sales.',
    decisionMakerProfile: 'Owner or Sales Manager.',
    painSignals: B2B_INDUSTRIAL_SIGNALS.pain,
    buyingSignals: B2B_INDUSTRIAL_SIGNALS.buying,
    aiOpportunitySignals: B2B_INDUSTRIAL_SIGNALS.ai,
    websiteOpportunitySignals: B2B_INDUSTRIAL_SIGNALS.web,
    automationOpportunitySignals: B2B_INDUSTRIAL_SIGNALS.automation,
    appSoftwareOpportunitySignals: B2B_INDUSTRIAL_SIGNALS.app,
    recommendedOffers: ['AI sales agent', 'lead follow-up', 'monitoring upsell', 'customer portal'],
    estimatedDealSize: { min: 4997, max: 15000, currency: 'USD', unit: 'monthly retainer' },
    outreachAngle: 'Security sales are relationship-driven — AI follow-up keeps installs and monitoring converting.',
  }),
  v({
    id: 'equipment_rental', name: 'Equipment Rental', category: 'B2B_INDUSTRIAL',
    icp: 'Equipment rental companies with availability inquiries and reservations.',
    decisionMakerProfile: 'Owner or Branch Manager.',
    painSignals: B2B_INDUSTRIAL_SIGNALS.pain,
    buyingSignals: B2B_INDUSTRIAL_SIGNALS.buying,
    aiOpportunitySignals: B2B_INDUSTRIAL_SIGNALS.ai,
    websiteOpportunitySignals: B2B_INDUSTRIAL_SIGNALS.web,
    automationOpportunitySignals: B2B_INDUSTRIAL_SIGNALS.automation,
    appSoftwareOpportunitySignals: B2B_INDUSTRIAL_SIGNALS.app,
    recommendedOffers: ['AI voice receptionist', 'reservation automation', 'missed-call recovery', 'rental app'],
    estimatedDealSize: { min: 4997, max: 15000, currency: 'USD', unit: 'monthly retainer' },
    outreachAngle: 'Rental equipment books on first call — AI answers availability and reserves units instantly.',
  }),
  v({
    id: 'wholesale', name: 'Wholesale Trade', category: 'B2B_INDUSTRIAL',
    icp: 'Wholesale traders with order pipelines and buyer follow-up.',
    decisionMakerProfile: 'Owner or Sales Director.',
    painSignals: B2B_INDUSTRIAL_SIGNALS.pain,
    buyingSignals: B2B_INDUSTRIAL_SIGNALS.buying,
    aiOpportunitySignals: B2B_INDUSTRIAL_SIGNALS.ai,
    websiteOpportunitySignals: B2B_INDUSTRIAL_SIGNALS.web,
    automationOpportunitySignals: B2B_INDUSTRIAL_SIGNALS.automation,
    appSoftwareOpportunitySignals: B2B_INDUSTRIAL_SIGNALS.app,
    recommendedOffers: ['AI sales agent', 'order automation', 'customer portal', 'supply-chain automation'],
    estimatedDealSize: { min: 5997, max: 25000, currency: 'USD', unit: 'monthly retainer' },
    outreachAngle: 'Buyers churn without follow-up — AI tracks orders and reorders to grow account value.',
  }),
];

export const DEFAULT_VERTICAL_CATALOG: VerticalDefinition[] = [
  ...HOME_SERVICES,
  ...HEALTH_WELLNESS,
  ...PROFESSIONAL_SERVICES,
  ...LOCAL_SERVICES,
  ...B2B_INDUSTRIAL,
];

export const CATEGORY_LABELS: Record<VerticalCategoryId, string> = {
  HOME_SERVICES: 'Home Services',
  HEALTH_WELLNESS: 'Health / Wellness',
  PROFESSIONAL_SERVICES: 'Professional Services',
  LOCAL_SERVICES: 'Local Services',
  B2B_INDUSTRIAL: 'B2B / Industrial',
};

export const CATEGORY_DEFAULT_WEIGHTS: Record<
  VerticalCategoryId,
  Record<keyof typeof HOME_SERVICE_SIGNALS, number>
> = {
  HOME_SERVICES: { pain: 0, buying: 0, ai: 0, web: 0, automation: 0, app: 0 },
  HEALTH_WELLNESS: { pain: 0, buying: 0, ai: 0, web: 0, automation: 0, app: 0 },
  PROFESSIONAL_SERVICES: { pain: 0, buying: 0, ai: 0, web: 0, automation: 0, app: 0 },
  LOCAL_SERVICES: { pain: 0, buying: 0, ai: 0, web: 0, automation: 0, app: 0 },
  B2B_INDUSTRIAL: { pain: 0, buying: 0, ai: 0, web: 0, automation: 0, app: 0 },
};