import * as fs from 'node:fs';
import * as path from 'node:path';
import PDFDocument from 'pdfkit';
import type { LeadExportRow, ExportResult } from './types';

const PAGE_MARGIN = 50;
const CONTENT_WIDTH = 495;

const GRADE_COLORS: Record<string, string> = {
  'A+': '#00B050',
  'A': '#92D050',
  'B': '#FFC000',
  'C': '#FF6600',
  'Reject': '#C00000',
};

const GRADE_BG: Record<string, string> = {
  'A+': '#D9F2D9',
  'A': '#EAF5E0',
  'B': '#FFF2CC',
  'C': '#FFE0CC',
  'Reject': '#F2D9D9',
};

interface GradeDistribution {
  grade: string;
  count: number;
  percentage: number;
}

function computeGradeDistribution(leads: LeadExportRow[]): GradeDistribution[] {
  const counts: Record<string, number> = {};
  for (const lead of leads) {
    counts[lead.grade] = (counts[lead.grade] ?? 0) + 1;
  }
  return Object.entries(counts)
    .map(([grade, count]) => ({
      grade,
      count,
      percentage: leads.length > 0 ? Math.round((count / leads.length) * 100) : 0,
    }))
    .sort((a, b) => {
      const order = ['A+', 'A', 'B', 'C', 'Reject'];
      return order.indexOf(a.grade) - order.indexOf(b.grade);
    });
}

function addFooter(doc: PDFKit.PDFDocument, pageNumber: number, timestamp: string): void {
  const bottomY = doc.page.height - 30;

  doc.fontSize(8)
    .fillColor('#888888');

  doc.text(
    `Generated by MBM Lead Engine | ${timestamp}`,
    PAGE_MARGIN,
    bottomY,
    { align: 'left', width: CONTENT_WIDTH / 2 },
  );

  doc.text(
    `Page ${pageNumber}`,
    PAGE_MARGIN,
    bottomY,
    { align: 'right', width: CONTENT_WIDTH },
  );

  doc.fillColor('#000000');
}

export async function generatePDF(
  leads: LeadExportRow[],
  filePath: string,
  headerText?: string,
  brandLogo?: string,
): Promise<ExportResult> {
  const dir = path.dirname(filePath);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }

  return new Promise<ExportResult>((resolve, reject) => {
    const ws = fs.createWriteStream(filePath);
    const doc = new PDFDocument({
      size: 'LETTER',
      margins: { top: 50, bottom: 50, left: 50, right: 50 },
      info: {
        Title: 'MBM Lead Engine - Lead Report',
        Author: 'MBM Lead Engine',
        Subject: 'Property Lead Report',
      },
    });

    let pageNumber = 1;
    const timestamp = new Date().toISOString().replace('T', ' ').slice(0, 19);

    doc.on('pageAdded', () => {
      pageNumber++;
      addFooter(doc, pageNumber, timestamp);
    });

    doc.pipe(ws);

    doc.on('error', (err) => reject(err));
    ws.on('error', (err) => reject(err));
    ws.on('finish', () => {
      try {
        const stats = fs.statSync(filePath);
        resolve({
          filePath,
          fileName: path.basename(filePath),
          fileSize: stats.size,
          mimeType: 'application/pdf',
          totalRecords: leads.length,
          generatedAt: new Date(),
        });
      } catch (err) {
        reject(err instanceof Error ? err : new Error(String(err)));
      }
    });

    // ── Title Page ──
    doc.fontSize(28)
      .fillColor('#2F5496')
      .text('MBM Lead Engine', PAGE_MARGIN, 180, { align: 'center', width: CONTENT_WIDTH });

    doc.fontSize(20)
      .fillColor('#333333')
      .text('Lead Report', PAGE_MARGIN, 220, { align: 'center', width: CONTENT_WIDTH });

    if (headerText) {
      doc.moveDown(2);
      doc.fontSize(14).fillColor('#555555').text(headerText, { align: 'center', width: CONTENT_WIDTH });
    }

    doc.moveDown(3);
    doc.fontSize(12).fillColor('#888888');

    const countyInfo = leads.length > 0 ? leads[0].county : 'N/A';
    doc.text(`County: ${countyInfo}`, { align: 'center', width: CONTENT_WIDTH });
    doc.text(`Records: ${leads.length}`, { align: 'center', width: CONTENT_WIDTH });
    doc.text(`Generated: ${timestamp}`, { align: 'center', width: CONTENT_WIDTH });

    doc.addPage();

    // ── Summary Section ──
    doc.fontSize(18)
      .fillColor('#2F5496')
      .text('Summary', PAGE_MARGIN, 60, { align: 'left', width: CONTENT_WIDTH });

    doc.moveDown(1);

    const avgScore = leads.length > 0
      ? Math.round(leads.reduce((s, l) => s + l.score, 0) / leads.length)
      : 0;
    const avgConfidence = leads.length > 0
      ? Math.round((leads.reduce((s, l) => s + l.confidence, 0) / leads.length) * 100) / 100
      : 0;

    const summaryData: { label: string; value: string }[] = [
      { label: 'Total Records', value: String(leads.length) },
      { label: 'Average Score', value: `${avgScore}/100` },
      { label: 'Average Confidence', value: `${(avgConfidence * 100).toFixed(1)}%` },
    ];

    let summaryY = doc.y;
    doc.fontSize(11).fillColor('#333333');
    for (const item of summaryData) {
      doc.text(`${item.label}:  ${item.value}`, PAGE_MARGIN, summaryY, { width: CONTENT_WIDTH });
      summaryY += 18;
    }

    // Grade distribution table
    doc.moveDown(2);
    const distribution = computeGradeDistribution(leads);
    const tableTop = doc.y;
    const colWidths = [80, 200, 100, 115];
    const tableHeaders = ['Grade', 'Count', 'Percentage', ''];

    // Table header
    let cx = PAGE_MARGIN;
    doc.fontSize(10).fillColor('#FFFFFF');
    for (let i = 0; i < tableHeaders.length; i++) {
      doc.rect(cx, tableTop, colWidths[i], 22).fill('#2F5496');
      doc.fillColor('#FFFFFF')
        .text(tableHeaders[i], cx + 5, tableTop + 5, { width: colWidths[i] - 10, align: i === 2 ? 'center' : 'left' });
      doc.fillColor('#FFFFFF');
      cx += colWidths[i];
    }

    // Table rows
    let rowY = tableTop + 22;
    for (const dist of distribution) {
      cx = PAGE_MARGIN;
      const bgColor = GRADE_BG[dist.grade] ?? '#FFFFFF';

      for (let i = 0; i < colWidths.length; i++) {
        doc.rect(cx, rowY, colWidths[i], 22).fill(bgColor);
        cx += colWidths[i];
      }

      cx = PAGE_MARGIN;
      doc.fillColor('#333333').fontSize(10);
      doc.text(dist.grade, cx + 5, rowY + 5, { width: colWidths[0] - 10 });
      cx += colWidths[0];
      doc.text(String(dist.count), cx + 5, rowY + 5, { width: colWidths[1] - 10 });
      cx += colWidths[1];
      doc.text(`${dist.percentage}%`, cx + 5, rowY + 5, { width: colWidths[2] - 10, align: 'center' });
      cx += colWidths[2];

      const barWidth = colWidths[3] - 20;
      const barHeight = 12;
      const barX = cx + 5;
      const barY = rowY + 5;
      doc.roundedRect(barX, barY, barWidth, barHeight, 3).fill('#E0E0E0');
      doc.roundedRect(barX, barY, barWidth * (dist.percentage / 100), barHeight, 3)
        .fill(GRADE_COLORS[dist.grade] ?? '#888888');

      rowY += 22;
    }

    // ── Lead Detail Pages ──
    for (let i = 0; i < leads.length; i++) {
      const lead = leads[i];

      // Check if we have enough space on current page (need ~150 points)
      if (doc.y > doc.page.height - 200) {
        doc.addPage();
      } else {
        doc.moveDown(2);
      }

      const startY = doc.y;

      // Score badge
      const badgeColor = GRADE_COLORS[lead.grade] ?? '#888888';
      const badgeText = `${lead.grade}  ${lead.score}`;

      doc.roundedRect(PAGE_MARGIN, startY, 100, 28, 4).fill(badgeColor);
      doc.fillColor('#FFFFFF')
        .fontSize(12)
        .text(badgeText, PAGE_MARGIN + 5, startY + 6, { width: 90, align: 'center' });

      // Lead header
      doc.fillColor('#2F5496')
        .fontSize(14)
        .text(`#${i + 1}  ${lead.address}`, PAGE_MARGIN + 115, startY + 4, {
          width: CONTENT_WIDTH - 115,
        });

      doc.fillColor('#888888')
        .fontSize(9)
        .text(`${lead.city}, ${lead.state} ${lead.zip}  |  ${lead.county} County  |  ${lead.parcelId}`,
          PAGE_MARGIN + 115, startY + 24, { width: CONTENT_WIDTH - 115 });

      const detailY = startY + 40;
      doc.moveDown(3);

      // Property details
      doc.fontSize(10).fillColor('#333333');
      const leftCol = PAGE_MARGIN;
      const rightCol = PAGE_MARGIN + 260;
      const lineHeight = 14;

      let ly = detailY;

      doc.fontSize(10).fillColor('#2F5496').text('Property', leftCol, ly);
      ly += 16;
      doc.fontSize(9).fillColor('#333333');
      doc.text(`Type: ${lead.propertyType}`, leftCol, ly);
      doc.text(`Year Built: ${lead.yearBuilt ?? 'N/A'}`, rightCol, ly);
      ly += lineHeight;
      doc.text(`Lot Size: ${lead.lotSize != null ? `${lead.lotSize.toLocaleString()} sqft` : 'N/A'}`, leftCol, ly);
      doc.text(`Building: ${lead.buildingSize != null ? `${lead.buildingSize.toLocaleString()} sqft` : 'N/A'}`, rightCol, ly);
      ly += lineHeight;
      doc.text(`Est. Value: ${lead.estimatedValue != null ? `$${lead.estimatedValue.toLocaleString()}` : 'N/A'}`, leftCol, ly);

      // Owner details
      ly += 20;
      doc.fontSize(10).fillColor('#2F5496').text('Owner', leftCol, ly);
      ly += 16;
      doc.fontSize(9).fillColor('#333333');
      doc.text(`Name: ${lead.ownerName}`, leftCol, ly);
      doc.text(`Type: ${lead.ownerType}`, rightCol, ly);
      ly += lineHeight;
      doc.text(`Mailing: ${lead.mailingAddress}`, leftCol, ly);
      doc.text(`Absentee: ${lead.isAbsentee ? 'Yes' : 'No'}`, rightCol, ly);

      // Lead details
      ly += 20;
      doc.fontSize(10).fillColor('#2F5496').text('Lead Intelligence', leftCol, ly);
      ly += 16;
      doc.fontSize(9).fillColor('#333333');
      doc.text(`Niche: ${lead.niche}`, leftCol, ly);
      doc.text(`Confidence: ${(lead.confidence * 100).toFixed(1)}%`, rightCol, ly);
      ly += lineHeight;
      doc.text(`Signals: ${lead.signals}`, leftCol, ly);
      ly += lineHeight;
      doc.text(`Source: ${lead.source}`, leftCol, ly);

      // Summary
      ly += 18;
      doc.fontSize(9).fillColor('#555555');
      doc.text(lead.summary, leftCol, ly, { width: CONTENT_WIDTH, align: 'left' });
    }

    // Add footer to last page
    addFooter(doc, pageNumber, timestamp);

    doc.end();
  });
}
