from MBM.ProductizedOffers.schema import ProductizedOffer

def get_catalog() -> list[ProductizedOffer]:
    return [
        ProductizedOffer(
            offer_id="offer_operational_strength",
            name="Operational Strength Audit",
            target_market="manufacturing, field service, automation, engineering, industrial suppliers",
            buyer_role="COO, VP Operations, Plant Manager",
            customer_job="Streamline Request -> Qualify -> Quote -> Approve -> Dispatch -> Close",
            problem_trigger="Coordination bottlenecks, manual data entry, lost requests",
            promised_outcome="Hypothesis: Identify coordination bottlenecks and produce a prioritized improvement plan + working demo",
            scope="Audit existing workflow steps and tools",
            deliverables=["Prioritized improvement plan", "Working demo"],
            proof_asset="Demo video of streamlined workflow",
            entry_offer_price=250.0,
            core_implementation_price=5000.0,
            qualification_criteria=["Experiences bottlenecks in request to dispatch"],
            rejection_criteria=["No existing workflow structure", "Not in target market"],
            approval_requirement="Operations team approval",
            payment_path="Neteller Rail",
            success_metric="Reduction in manual steps",
            retention_path="Managed service maintenance"
        ),
        ProductizedOffer(
            offer_id="offer_revenue_leak",
            name="Revenue Leak / Sales Pipeline Audit",
            target_market="staffing, recruiting, B2B services, agencies, distributors, professional services",
            buyer_role="VP Sales, CRO, Sales Director",
            customer_job="Close more qualified leads",
            problem_trigger="Leads dropping between discovery and close",
            promised_outcome="Hypothesis: Identify leakage across the entire sales lifecycle",
            scope="Audit lead discovery, qualification, follow-up, proposal, close, onboarding",
            deliverables=["Leakage report", "Actionable fix plan"],
            proof_asset="Pipeline diagnostic dashboard demo",
            entry_offer_price=250.0,
            core_implementation_price=3000.0,
            qualification_criteria=["Active inbound/outbound pipeline", "Revenue > $1M"],
            rejection_criteria=["No sales team", "No CRM"],
            approval_requirement="Sales leadership approval",
            payment_path="Neteller Rail",
            success_metric="Increase in pipeline conversion rate",
            retention_path="Monthly pipeline review"
        ),
        ProductizedOffer(
            offer_id="offer_ai_sales_enablement",
            name="AI Sales Enablement Pack",
            target_market="service businesses and B2B teams",
            buyer_role="Sales Manager, VP Sales",
            customer_job="Equip sales team with targeted assets and data",
            problem_trigger="Low outbound conversion, generic messaging",
            promised_outcome="Hypothesis: Equip team with personalized outreach and decision-maker maps",
            scope="Provide ICP lists, personalized assets, and outreach angles",
            deliverables=["ICP/account list", "Decision-maker map", "Personalized outreach angles", "Sales deck/one-pager", "Objection map", "Demo asset", "Follow-up sequence"],
            proof_asset="Sample personalized outreach and map",
            entry_offer_price=500.0,
            core_implementation_price=2500.0,
            qualification_criteria=["Active outbound motion"],
            rejection_criteria=["B2C focus"],
            approval_requirement="Sales leadership approval",
            payment_path="Neteller Rail",
            success_metric="Increase in positive reply rate",
            retention_path="Managed service for ongoing lists"
        ),
        ProductizedOffer(
            offer_id="offer_atlassian_hardening",
            name="Atlassian Knowledge + Workflow Hardening",
            target_market="Jira/Confluence-heavy teams",
            buyer_role="CTO, VP Engineering, Product Operations",
            customer_job="Improve documentation retrieval and project visibility",
            problem_trigger="Lost knowledge, messy handoffs",
            promised_outcome="Hypothesis: Improve workflow clarity, documentation retrieval, and handoffs",
            scope="Audit and restructure Jira/Confluence operations",
            deliverables=["Restructured workflow plan", "Knowledge retrieval integration"],
            proof_asset="Demo of Rovo finding hidden documentation",
            entry_offer_price=500.0,
            core_implementation_price=7500.0,
            qualification_criteria=["Uses Jira/Confluence actively"],
            rejection_criteria=["Uses different stack (Asana/Notion)"],
            approval_requirement="Engineering/Product leadership approval",
            payment_path="Neteller Rail",
            success_metric="Reduction in search time / improved velocity",
            retention_path="Ongoing knowledge operations management"
        )
    ]
